### ISSUE TITLE
WANTED: Baron Vardus

### ISSUE THREAD

**Issue by mickwow** [ValorenWoW/sunstrider-core#4526]
**Describe the bug**
This quest is supposed to have a level requirement of 18, however it does not.
It should be changed to minimum level 18 to pick up this quest.
I have played many TBC wow private servers and they all had level 18.
You can even check wowhead here: https://www.wowhead.com/quest=566/deprecated-wanted-baron-vardus

**Character name**
N/A

**To Reproduce**

N/A

https://www.wowhead.com/quest=566/deprecated-wanted-baron-vardus

**Expected behavior**
Quest should be obtainable at level 18.

**Screenshots/videos**
N/A

**Additional context**
N/A

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.

**Comment by mickwow** [comment]
Hello, i believe the server has been restarted since and yet the quest still cannot be obtained at the appropriate level.
Can you please look into this? Many thanks.

**Comment by mickwow** [comment]
Im sorry, my bad...i was looking at the wrong wanted poster.

Thank you so much for your efforts!
