### ISSUE TITLE
quest problem: The Force of neltharaku

### ISSUE THREAD

**Issue by LordSmok** [ValorenWoW/sunstrider-core#4971]
Quest dsn't work, when I use quest item on enslaved  drake it flies up, disappears, and immediately respawns/

Character: Smok

**To Reproduce**
simply try to do the q

Item: https://www.wowhead.com/item=31652/enchanted-nethervine-crystal
Quest: https://www.wowhead.com/quest=10854/the-force-of-neltharaku

**Expected behavior**
from what gm told me it is enough to use item on a mob.

**Additional context**
I tried everything doing it solo or in party (with other ppl that had the q, for them it also didn't work), abandoning and retaking the q, luring ork npc to the drake and using item on a drake, waiting for npc that is not in combat to getting close to drake and then using the q-item, killing drake, using item and then killing drake, using item and beat drake to <10%hp
still nothing worked

with regards
LordSmok

**Comment by sholim** [comment]
+ bumb, quest is still not working. there is no possible way to free enslaved drake.

**Comment by Jerrythemagicdog** [comment]
Fixed with the latest update, thanks for the issue.

**Comment by sholim** [comment]
for me its still not working... or mb i didnt find a way on how to compete it
