### ISSUE TITLE
Mind Control trigger guards to attack incorrect target

### ISSUE THREAD

**Issue by miki-g** [ValorenWoW/sunstrider-core#5092]
[Mind Control](https://db.endless.gg/?spell=10912) trigger guards to attack incorrect target, they kill controlled player instead of priest (then also kill priest)
but killing ( inactive / passive ) controled player is wrong

thanks

(: & shadow priest with nick [funnin](https://endless.gg/armory/character/funnin) need some /slap-s /kick-s and /ban for using this bug on Isle of Quel'Danas :)
it is character without equip used only for ruin game for others => ready to ban

**Comment by kelno** [comment]
Thanks, fixed with next server update

**Comment by miki-g** [comment]
not fixed after update
characters Funnin and Moopidstams again using this bug on Isle of Quel'Danas

**Comment by kelno** [comment]
The server wasn't updated since. I'll restart the server with the update now

**Comment by miki-g** [comment]
(: ok, thanks & sorry, i thought the restart was also with an update :)
