### ISSUE TITLE
Can't learn transmog appearance "while it's still tradeable" even though it's not

### ISSUE THREAD

**Issue by miranda** [ValorenWoW/sunstrider-core#5569]
Tradeability status has expired yet I cannot learn the appearance of this item no matter what I do...

![2023-11-02-145903_3840x2160_scrot](https://github.com/SunstriderEmu/BugTracker/assets/83934/b3bdeb05-d62f-4c3d-85f1-b47fd28593dc)

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, should be resolved now!

**Comment by dmiric** [comment]
It's not I still can't do it. I have a claw in my bank for 2 days can't learn the appearance.

**Comment by Tanatsuko** [comment]
I had the same happen with my Ravager on my paladin. I just tried it again the next day, and then it worked. Doesn't seem to be fixed.

**Comment by kelno** [comment]
Fixed with next server update

**Comment by Jerrythemagicdog** [comment]
Issue resolved since then.
